name: PM

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: coq-community/docker-coq-action@v1
      with:
        custom_image: coqorg/coq:8.20-ocaml-4.14-flambda
        custom_script: |
          startGroup "Build"
            sudo chown -R $(whoami) .
            # cd ${{ github.workspace }}
            pwd
            time make
          endGroup